baseurl = "https://bluele.github.io/" # TODO
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Jun Kimura"
title = "Jun Kimura"
pygmentsuseclasses = true
# disqusShortname = "cocoaexamplesite" # TODO: optional, comment out to disable Disqus
pluralizelisttitles = false
theme = "cocoa"

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "JUN KIMURA"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "JUN KIMURA BLOG"
Email = "junkxdev@gmail.com"
FaviconFile = "img/leaf.ico"
GATracker = "UA-75041083-1"
GitHub = "//github.com/bluele"
Facebook = "//facebook.com/jkimura0818"
Initials = "ad" # displayed on single post page; DEPRECATED in v0.3.0
Lang = "en"
LinkedIn = "//www.linkedin.com/in/jun-kimura-5a969352"
Twitter = "//twitter.com/bluele_jp"
ExtraCssFiles = [ "/css/override.css" ] # relative to public directory
